### ISSUE TITLE
dont boot on amd64

### ISSUE THREAD

**Issue by fpusersuggest** [ykaw/FuguIta#1]
Hello, I downloaded the img with wget in this way:
```
$ wget https://de.dl.fuguita.org/FuguIta-7.1-amd64-202205241.img.gz
```
then I burn the img to a usb microsd with dd from freebsd in this way:
```
# dd if=myfuguita.img of=/dev/da0 conv=sync bs=1M status=progress
```
after that I reboot my freebsd box. 
But looks that some files for boot are missing.
it cannot boot because miss bsd-fi.mp or bsd-fi files.. that file looks broken link to something like bsd-fi_some_number on the usb stick.

**Comment by ykaw** [comment]
I have also confirmed the failure you reported here.
I generated again FuguIta-7.1-amd64-202205241 from FuguIta-7.1-amd64-202205241.iso using the usbfadm utility and confirmed that it works correctly.
The mirror site update has also been completed.

Grazie per la sua relazione.
