### ISSUE TITLE
Fatal error during GPU init - Failed to load firmware "radeon/MULLINS_pfp.bin"

### ISSUE THREAD

**Issue by Veraellyunjie** [ykaw/FuguIta#2]
![amdgpu](https://github.com/ykaw/FuguIta/assets/75799052/5ab1c3ae-a732-4105-8117-3eb0b0401749)

FuguIta-7.4-amd64-202404091.img.gz

Mobo is [Asrock QC6000M](https://www.asrock.com/mb/AMD/QC6000M/index.asp) with Integrated AMD Radeon™ R2 Graphics.

OpenBSD and X do work on this machine

**Comment by ykaw** [comment]
This is a known issue.

This is because FuguIta's root file system is the kernel's built-in rd(4), "ramdisk root."

For more further details, read https://fuguita.org/?FuguIta/BBS#od721234 .
